import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

// Components
import Banner from '../components/Banner';

// Images
import ImgCover from '../assets/images/cover.webp';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DMC - Advogados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner
          src={ImgCover}
          alt="DMC"
        />
      </main>
    </div>
  )
}

export default Home
