import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

// Components
import Header from '../components/Header';
import Banner from '../components/Banner';

// Images
import ImgCoverDesktop from '../assets/images/cover.webp';
import ImgCoverMobile from '../assets/images/cover-mb.webp';
import Logo from '../assets/images/logo.webp';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DMC - Advogados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <Header 
          logo={Logo}
          logoAlt="Duarte Matos e Carvalho"
        />
        <Banner
          srcDesktop={ImgCoverDesktop}
          srcMobile={ImgCoverMobile}
          alt="DMC"
        />
      </main>
    </div>
  )
}

export default Home
